AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  Kaki:
    Type: String
Resources:
  WebsiteBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Join ['', ['website-bucket-cf-', !Ref Kaki, !Select [2, !Split ['/', !Ref AWS::StackId]]]]
      AccessControl: 'PublicRead'
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
  WebsiteBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: Allow-Public-Access-To-Bucket
            Effect: Allow
            Principal:
              AWS: '*'
            Action:
              - s3:GetObject
            Resource:
              - !Join ['', ['arn:aws:s3:::', !Ref WebsiteBucket, '/*']]

  WebsiteBucket2:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Join ['', ['website-bucket-cf-2-', !Ref Kaki, !Select [2, !Split ['/', !Ref AWS::StackId]]]]
      AccessControl: 'PublicRead'
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
  WebsiteBucketPolicy2:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref WebsiteBucket2
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: Allow-Public-Access-To-Bucket
            Effect: Allow
            Principal:
              AWS: '*'
            Action:
              - s3:GetObject
            Resource:
              - !Join ['', ['arn:aws:s3:::', !Ref WebsiteBucket2, '/*']]
              
  WebsiteBucket3:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Join ['', ['website-bucket-cf-3-', !Ref Kaki, !Select [2, !Split ['/', !Ref AWS::StackId]]]]
      AccessControl: 'PublicRead'
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
  WebsiteBucketPolicy3:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref WebsiteBucket3
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: Allow-Public-Access-To-Bucket
            Effect: Allow
            Principal:
              AWS: '*'
            Action:
              - s3:GetObject
            Resource:
              - !Join ['', ['arn:aws:s3:::', !Ref WebsiteBucket3, '/*']]
              
  WebsiteBucket4:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Join ['', ['website-bucket-cf-4-', !Ref Kaki, !Select [2, !Split ['/', !Ref AWS::StackId]]]]
      AccessControl: 'PublicRead'
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
  WebsiteBucketPolicy4:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref WebsiteBucket4
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: Allow-Public-Access-To-Bucket
            Effect: Allow
            Principal:
              AWS: '*'
            Action:
              - s3:GetObject
            Resource:
              - !Join ['', ['arn:aws:s3:::', !Ref WebsiteBucket4, '/*']]
              
  WebsiteBucket5:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Join ['', ['website-bucket-cf-5-', !Ref Kaki, !Select [2, !Split ['/', !Ref AWS::StackId]]]]
      AccessControl: 'PublicRead'
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
  WebsiteBucketPolicy5:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref WebsiteBucket5
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: Allow-Public-Access-To-Bucket
            Effect: Allow
            Principal:
              AWS: '*'
            Action:
              - s3:GetObject
            Resource:
              - !Join ['', ['arn:aws:s3:::', !Ref WebsiteBucket5, '/*']]
              
  WebsiteBucket6:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Join ['', ['website-bucket-cf-6-', !Ref Kaki, !Select [2, !Split ['/', !Ref AWS::StackId]]]]
      AccessControl: 'PublicRead'
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
  WebsiteBucketPolicy6:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref WebsiteBucket6
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: Allow-Public-Access-To-Bucket
            Effect: Allow
            Principal:
              AWS: '*'
            Action:
              - s3:GetObject
            Resource:
              - !Join ['', ['arn:aws:s3:::', !Ref WebsiteBucket6, '/*']]
Outputs:
  BucketUrl:
    Value: !GetAtt WebsiteBucket.WebsiteURL
    Description: 'URL of the S3 bucket'
  BucketUrl2:
    Value: !GetAtt WebsiteBucket2.WebsiteURL
    Description: 'URL of the S3 bucket'
  BucketUrl3:
    Value: !GetAtt WebsiteBucket3.WebsiteURL
    Description: 'URL of the S3 bucket'
  BucketUrl4:
    Value: !GetAtt WebsiteBucket4.WebsiteURL
    Description: 'URL of the S3 bucket'
  BucketUrl5:
    Value: !GetAtt WebsiteBucket5.WebsiteURL
    Description: 'URL of the S3 bucket'
  BucketUrl6:
    Value: !GetAtt WebsiteBucket6.WebsiteURL
    Description: 'URL of the S3 bucket'
    
